version: "3"
services:
  api-server:
    build: ./
    env_file: ./config/config.env
    ports:
      - "3080:3000"
    networks:
      - jp-storybooks-app 
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6-xenial
    environment:
      - MONGO_INITDB_DATABASE=jp-storybooks-app
    ports:
      - "27017:27017"
    networks:
      - jp-storybooks-app
    volumes:
      - mongo-data:/data/db
networks:
  jp-storybooks-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
